#!/bin/bash
# Modified by PastureStack contributors for independent maintenance and rebranding.
set -euo pipefail

source $(dirname $0)/version

cd $(dirname $0)/..

rm -rf bin/*

mkdir -p bin
CGO_ENABLED=0 go build \
    -trimpath \
    -buildvcs=false \
    -ldflags "-buildid= -X main.VERSION=$VERSION -s -w" \
    -o bin/ecr-credential-sync

declare -A OS_ARCH_ARG=()

OS_PLATFORM_ARG=(linux windows)
OS_ARCH_ARG[linux]="amd64"
OS_ARCH_ARG[windows]="amd64"

if [ -n "${CROSS:-}" ]; then
    for OS in ${OS_PLATFORM_ARG[@]}; do
        for ARCH in ${OS_ARCH_ARG[${OS}]}; do
            OUTPUT_BIN="bin/$OS/$ARCH/ecr-credential-sync"
            if test "$OS" = "windows"; then
                OUTPUT_BIN="${OUTPUT_BIN}.exe"
            fi
            echo "Building binary for $OS/$ARCH..."
            GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build \
                  -trimpath \
                  -buildvcs=false \
                  -ldflags="-buildid= -X main.VERSION=$VERSION -s -w" \
                  -o ${OUTPUT_BIN} ./
        done
    done
fi
