#!/bin/bash
set -euo pipefail

cd $(dirname $0)/..

echo Running tests

PACKAGES=$(go list -mod=vendor ./... | grep -Ev '(/vendor/|/mocks$)' || true)
RACE=${RACE:-}

[ "${ARCH}" == "amd64" ] && RACE=-race
go test -mod=vendor ${RACE} -cover -tags=test ${PACKAGES}
