#!/bin/bash
set -euo pipefail

cd $(dirname $0)/..

echo Running validation

PACKAGES=$(go list ./... | grep -Ev '(/vendor/|/mocks$)' || true)

echo Running: go vet
go vet ${PACKAGES}
echo Running: go fmt
test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"
